# Change these first
owner: Rytale # Your GitHub organization or username
repo: Statuspage-v2 # Your GitHub repository name

# Add your sites here
sites:
  - name: Rytale
    url: https://Rytale.net
  - name: Discord-bot
    url: $SECRET_SITE
  - name: TCP ping
    url: 1.1.1.1
i18n:
activeIncidents: Active Incidents
allSystemsOperational: All systems are operational
incidentReport: "Incident #$NUMBER report →"
activeIncidentSummary: Opened at $DATE with $POSTS posts
incidentTitle: Incident $NUMBER Details
incidentDetails: Incident Details
incidentFixed: Fixed
incidentOngoing: Ongoing
incidentOpenedAt: Opened at
incidentClosedAt: Closed at
incidentSubscribe: Subscribe to Updates
incidentViewOnGitHub: View on GitHub
incidentCommentSummary: Posted at $DATE by $AUTHOR
incidentBack: ← Back to all incidents
pastIncidents: Past Incidents
pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
liveStatus: Live Status
overallUptime: "Overall uptime: $UPTIME"
overallUptimeTitle: Overall uptime
averageResponseTime: "Average response time: $TIMEms"
averageResponseTimeTitle: Average response
sevelDayResponseTime: 7-day response time
responseTimeMs: Response time (ms)
up: Up
down: Down
degraded: Degraded
ms: ms
loading: Loading
navGitHub: GitHub
footer: Tadsadasdasdasdasdasd
rateLimitExceededTitle: Rate limit exceedeed
rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
rateLimitExceededWhatDoesErrorMean: What does this error mean?
rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
rateLimitExceededErrorHowCanFix: How can I fix it?
rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
rateLimitExceededHasSet: You have a personal access token set.
rateLimitExceededRemoveToken: Remove token
rateLimitExceededGitHubPAT: GitHub Personal Access Token
rateLimitExceededCopyPastePAT: Copy and paste your token
rateLimitExceededSaveToken: Save token
errorTitle: An error occurred
errorIntro: An error occurred in trying to get the latest status details.
errorText: You can try again in a few moments.
errorHome: Go to the homepage
pastScheduledMaintenance: Past Scheduled Maintenance
scheduledMaintenance: Scheduled Maintenance
scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
startedAt: Started at
startsAt: Starts at
duration: Duration
durationMin: $DURATION minutes
incidentCompleted: Completed
incidentScheduled: Scheduled
status-website:
  theme: night
  # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /Statuspage-v2
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rytale-Statuspage
  introTitle: "**Rytale** Network status page"
  introMessage: 
  i18n:
    footer: Copyright © 2021 Rytale
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://rytale.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
