# Change these first
owner: Rytale # Your GitHub organization or username
repo: Statuspage-v2 # Your GitHub repository name

# Add your sites here
sites:
  - name: Rytale
    url: https://Rytale.net
  - name: Discord-bot
    url: $SECRET_SITE
  - name: TCP ping
    url: 1.1.1.1

status-website:
  theme: dark
  # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /Statuspage-v2
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rytale-Statuspage
  introTitle: "**Rytale** Network status page"
  introMessage: 
  i18n:
  footer: Copyright © 2021 Rytale
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://rytale.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
